/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  AuthPayload: { // root type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Card: { // root type
    answer: string; // String!
    cardId: number; // Int!
    category: string; // String!
    isDone: boolean; // Boolean!
    question: string; // String!
  }
  Mutation: {};
  Query: {};
  User: { // root type
    email: string; // String!
    id: number; // Int!
    name: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  AuthPayload: { // field return type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Card: { // field return type
    answer: string; // String!
    cardId: number; // Int!
    category: string; // String!
    isDone: boolean; // Boolean!
    postedBy: NexusGenRootTypes['User'] | null; // User
    question: string; // String!
  }
  Mutation: { // field return type
    delete: NexusGenRootTypes['Card']; // Card!
    login: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    markAsDone: NexusGenRootTypes['Card']; // Card!
    post: NexusGenRootTypes['Card']; // Card!
    signup: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    update: NexusGenRootTypes['Card']; // Card!
  }
  Query: { // field return type
    feed: NexusGenRootTypes['Card'][]; // [Card!]!
    feedById: NexusGenRootTypes['Card'] | null; // Card
    getDoneCards: NexusGenRootTypes['Card'][]; // [Card!]!
  }
  User: { // field return type
    cards: NexusGenRootTypes['Card'][]; // [Card!]!
    email: string; // String!
    id: number; // Int!
    name: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  AuthPayload: { // field return type name
    token: 'String'
    user: 'User'
  }
  Card: { // field return type name
    answer: 'String'
    cardId: 'Int'
    category: 'String'
    isDone: 'Boolean'
    postedBy: 'User'
    question: 'String'
  }
  Mutation: { // field return type name
    delete: 'Card'
    login: 'AuthPayload'
    markAsDone: 'Card'
    post: 'Card'
    signup: 'AuthPayload'
    update: 'Card'
  }
  Query: { // field return type name
    feed: 'Card'
    feedById: 'Card'
    getDoneCards: 'Card'
  }
  User: { // field return type name
    cards: 'Card'
    email: 'String'
    id: 'Int'
    name: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    delete: { // args
      cardId: number; // Int!
    }
    login: { // args
      email: string; // String!
      password: string; // String!
    }
    markAsDone: { // args
      cardId: number; // Int!
    }
    post: { // args
      answer: string; // String!
      category: string; // String!
      question: string; // String!
    }
    signup: { // args
      email: string; // String!
      name: string; // String!
      password: string; // String!
    }
    update: { // args
      answer: string; // String!
      cardId: number; // Int!
      category: string; // String!
      question: string; // String!
    }
  }
  Query: {
    feed: { // args
      category?: string | null; // String
    }
    feedById: { // args
      cardId: number; // Int!
    }
    getDoneCards: { // args
      isDone?: boolean | null; // Boolean
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}